; generated by prob2pddl.py 10x12-ps1-d22.prob
;   ######  
;   #O  O#  
; ####  ####
; # L    Y #
; #CPR  BPC#
; ####  ####
; # O    OY#
; #OGB  BPG#
; ####  ####
;   ##PR##  
;   ##RL##  
;   ######  
; O:5 P:4 R:3 B:3 Y:2 G:2 C:2 L:2 blocks:23 spaces:43
(define (problem puzznic36)
(:domain puzznic)

    (:objects
        red - pattern
        orange - pattern
        yellow - pattern
        green - pattern
        blue - pattern
        violet - pattern
        pink - pattern
        coal - pattern
        lightblue - pattern
        loc_1_1 - location
        loc_2_1 - location
        loc_3_1 - location
        loc_4_1 - location
        loc_5_1 - location
        loc_6_1 - location
        loc_7_1 - location
        loc_8_1 - location
        loc_9_1 - location
        loc_10_1 - location
        loc_1_2 - location
        loc_2_2 - location
        loc_3_2 - location
        loc_4_2 - location
        loc_5_2 - location
        loc_6_2 - location
        loc_7_2 - location
        loc_8_2 - location
        loc_9_2 - location
        loc_10_2 - location
        loc_1_3 - location
        loc_2_3 - location
        loc_3_3 - location
        loc_4_3 - location
        loc_5_3 - location
        loc_6_3 - location
        loc_7_3 - location
        loc_8_3 - location
        loc_9_3 - location
        loc_10_3 - location
        loc_1_4 - location
        loc_2_4 - location
        loc_3_4 - location
        loc_4_4 - location
        loc_5_4 - location
        loc_6_4 - location
        loc_7_4 - location
        loc_8_4 - location
        loc_9_4 - location
        loc_10_4 - location
        loc_1_5 - location
        loc_2_5 - location
        loc_3_5 - location
        loc_4_5 - location
        loc_5_5 - location
        loc_6_5 - location
        loc_7_5 - location
        loc_8_5 - location
        loc_9_5 - location
        loc_10_5 - location
        loc_1_6 - location
        loc_2_6 - location
        loc_3_6 - location
        loc_4_6 - location
        loc_5_6 - location
        loc_6_6 - location
        loc_7_6 - location
        loc_8_6 - location
        loc_9_6 - location
        loc_10_6 - location
        loc_1_7 - location
        loc_2_7 - location
        loc_3_7 - location
        loc_4_7 - location
        loc_5_7 - location
        loc_6_7 - location
        loc_7_7 - location
        loc_8_7 - location
        loc_9_7 - location
        loc_10_7 - location
        loc_1_8 - location
        loc_2_8 - location
        loc_3_8 - location
        loc_4_8 - location
        loc_5_8 - location
        loc_6_8 - location
        loc_7_8 - location
        loc_8_8 - location
        loc_9_8 - location
        loc_10_8 - location
        loc_1_9 - location
        loc_2_9 - location
        loc_3_9 - location
        loc_4_9 - location
        loc_5_9 - location
        loc_6_9 - location
        loc_7_9 - location
        loc_8_9 - location
        loc_9_9 - location
        loc_10_9 - location
        loc_1_10 - location
        loc_2_10 - location
        loc_3_10 - location
        loc_4_10 - location
        loc_5_10 - location
        loc_6_10 - location
        loc_7_10 - location
        loc_8_10 - location
        loc_9_10 - location
        loc_10_10 - location
        loc_1_11 - location
        loc_2_11 - location
        loc_3_11 - location
        loc_4_11 - location
        loc_5_11 - location
        loc_6_11 - location
        loc_7_11 - location
        loc_8_11 - location
        loc_9_11 - location
        loc_10_11 - location
        loc_1_12 - location
        loc_2_12 - location
        loc_3_12 - location
        loc_4_12 - location
        loc_5_12 - location
        loc_6_12 - location
        loc_7_12 - location
        loc_8_12 - location
        loc_9_12 - location
        loc_10_12 - location
)
    (:init
        (= (total-cost) 0)
        (next loc_1_1 loc_2_1 right)
        (next loc_1_1 loc_1_2 up)
        (next loc_2_1 loc_1_1 left)
        (next loc_2_1 loc_2_2 up)
        (next loc_9_1 loc_10_1 right)
        (next loc_9_1 loc_9_2 up)
        (next loc_10_1 loc_9_1 left)
        (next loc_10_1 loc_10_2 up)
        (next loc_1_2 loc_2_2 right)
        (next loc_1_2 loc_1_3 up)
        (next loc_1_2 loc_1_1 down)
        (next loc_2_2 loc_1_2 left)
        (next loc_2_2 loc_2_3 up)
        (next loc_2_2 loc_2_1 down)
        (next loc_5_2 loc_6_2 right)
        (next loc_5_2 loc_5_3 up)
        (next loc_6_2 loc_5_2 left)
        (next loc_6_2 loc_6_3 up)
        (next loc_9_2 loc_10_2 right)
        (next loc_9_2 loc_9_3 up)
        (next loc_9_2 loc_9_1 down)
        (next loc_10_2 loc_9_2 left)
        (next loc_10_2 loc_10_3 up)
        (next loc_10_2 loc_10_1 down)
        (next loc_1_3 loc_2_3 right)
        (next loc_1_3 loc_1_2 down)
        (next loc_2_3 loc_1_3 left)
        (next loc_2_3 loc_2_2 down)
        (next loc_5_3 loc_6_3 right)
        (next loc_5_3 loc_5_4 up)
        (next loc_5_3 loc_5_2 down)
        (next loc_6_3 loc_5_3 left)
        (next loc_6_3 loc_6_4 up)
        (next loc_6_3 loc_6_2 down)
        (next loc_9_3 loc_10_3 right)
        (next loc_9_3 loc_9_2 down)
        (next loc_10_3 loc_9_3 left)
        (next loc_10_3 loc_10_2 down)
        (next loc_5_4 loc_6_4 right)
        (next loc_5_4 loc_5_5 up)
        (next loc_5_4 loc_5_3 down)
        (next loc_6_4 loc_5_4 left)
        (next loc_6_4 loc_6_5 up)
        (next loc_6_4 loc_6_3 down)
        (next loc_2_5 loc_3_5 right)
        (next loc_2_5 loc_2_6 up)
        (next loc_3_5 loc_2_5 left)
        (next loc_3_5 loc_4_5 right)
        (next loc_3_5 loc_3_6 up)
        (next loc_4_5 loc_3_5 left)
        (next loc_4_5 loc_5_5 right)
        (next loc_4_5 loc_4_6 up)
        (next loc_5_5 loc_4_5 left)
        (next loc_5_5 loc_6_5 right)
        (next loc_5_5 loc_5_6 up)
        (next loc_5_5 loc_5_4 down)
        (next loc_6_5 loc_5_5 left)
        (next loc_6_5 loc_7_5 right)
        (next loc_6_5 loc_6_6 up)
        (next loc_6_5 loc_6_4 down)
        (next loc_7_5 loc_6_5 left)
        (next loc_7_5 loc_8_5 right)
        (next loc_7_5 loc_7_6 up)
        (next loc_8_5 loc_7_5 left)
        (next loc_8_5 loc_9_5 right)
        (next loc_8_5 loc_8_6 up)
        (next loc_9_5 loc_8_5 left)
        (next loc_9_5 loc_9_6 up)
        (next loc_2_6 loc_3_6 right)
        (next loc_2_6 loc_2_5 down)
        (next loc_3_6 loc_2_6 left)
        (next loc_3_6 loc_4_6 right)
        (next loc_3_6 loc_3_5 down)
        (next loc_4_6 loc_3_6 left)
        (next loc_4_6 loc_5_6 right)
        (next loc_4_6 loc_4_5 down)
        (next loc_5_6 loc_4_6 left)
        (next loc_5_6 loc_6_6 right)
        (next loc_5_6 loc_5_7 up)
        (next loc_5_6 loc_5_5 down)
        (next loc_6_6 loc_5_6 left)
        (next loc_6_6 loc_7_6 right)
        (next loc_6_6 loc_6_7 up)
        (next loc_6_6 loc_6_5 down)
        (next loc_7_6 loc_6_6 left)
        (next loc_7_6 loc_8_6 right)
        (next loc_7_6 loc_7_5 down)
        (next loc_8_6 loc_7_6 left)
        (next loc_8_6 loc_9_6 right)
        (next loc_8_6 loc_8_5 down)
        (next loc_9_6 loc_8_6 left)
        (next loc_9_6 loc_9_5 down)
        (next loc_5_7 loc_6_7 right)
        (next loc_5_7 loc_5_8 up)
        (next loc_5_7 loc_5_6 down)
        (next loc_6_7 loc_5_7 left)
        (next loc_6_7 loc_6_8 up)
        (next loc_6_7 loc_6_6 down)
        (next loc_2_8 loc_3_8 right)
        (next loc_2_8 loc_2_9 up)
        (next loc_3_8 loc_2_8 left)
        (next loc_3_8 loc_4_8 right)
        (next loc_3_8 loc_3_9 up)
        (next loc_4_8 loc_3_8 left)
        (next loc_4_8 loc_5_8 right)
        (next loc_4_8 loc_4_9 up)
        (next loc_5_8 loc_4_8 left)
        (next loc_5_8 loc_6_8 right)
        (next loc_5_8 loc_5_9 up)
        (next loc_5_8 loc_5_7 down)
        (next loc_6_8 loc_5_8 left)
        (next loc_6_8 loc_7_8 right)
        (next loc_6_8 loc_6_9 up)
        (next loc_6_8 loc_6_7 down)
        (next loc_7_8 loc_6_8 left)
        (next loc_7_8 loc_8_8 right)
        (next loc_7_8 loc_7_9 up)
        (next loc_8_8 loc_7_8 left)
        (next loc_8_8 loc_9_8 right)
        (next loc_8_8 loc_8_9 up)
        (next loc_9_8 loc_8_8 left)
        (next loc_9_8 loc_9_9 up)
        (next loc_2_9 loc_3_9 right)
        (next loc_2_9 loc_2_8 down)
        (next loc_3_9 loc_2_9 left)
        (next loc_3_9 loc_4_9 right)
        (next loc_3_9 loc_3_8 down)
        (next loc_4_9 loc_3_9 left)
        (next loc_4_9 loc_5_9 right)
        (next loc_4_9 loc_4_8 down)
        (next loc_5_9 loc_4_9 left)
        (next loc_5_9 loc_6_9 right)
        (next loc_5_9 loc_5_10 up)
        (next loc_5_9 loc_5_8 down)
        (next loc_6_9 loc_5_9 left)
        (next loc_6_9 loc_7_9 right)
        (next loc_6_9 loc_6_10 up)
        (next loc_6_9 loc_6_8 down)
        (next loc_7_9 loc_6_9 left)
        (next loc_7_9 loc_8_9 right)
        (next loc_7_9 loc_7_8 down)
        (next loc_8_9 loc_7_9 left)
        (next loc_8_9 loc_9_9 right)
        (next loc_8_9 loc_8_8 down)
        (next loc_9_9 loc_8_9 left)
        (next loc_9_9 loc_9_8 down)
        (next loc_5_10 loc_6_10 right)
        (next loc_5_10 loc_5_11 up)
        (next loc_5_10 loc_5_9 down)
        (next loc_6_10 loc_5_10 left)
        (next loc_6_10 loc_6_11 up)
        (next loc_6_10 loc_6_9 down)
        (next loc_1_11 loc_2_11 right)
        (next loc_1_11 loc_1_12 up)
        (next loc_2_11 loc_1_11 left)
        (next loc_2_11 loc_2_12 up)
        (next loc_4_11 loc_5_11 right)
        (next loc_5_11 loc_4_11 left)
        (next loc_5_11 loc_6_11 right)
        (next loc_5_11 loc_5_10 down)
        (next loc_6_11 loc_5_11 left)
        (next loc_6_11 loc_7_11 right)
        (next loc_6_11 loc_6_10 down)
        (next loc_7_11 loc_6_11 left)
        (next loc_9_11 loc_10_11 right)
        (next loc_9_11 loc_9_12 up)
        (next loc_10_11 loc_9_11 left)
        (next loc_10_11 loc_10_12 up)
        (next loc_1_12 loc_2_12 right)
        (next loc_1_12 loc_1_11 down)
        (next loc_2_12 loc_1_12 left)
        (next loc_2_12 loc_2_11 down)
        (next loc_9_12 loc_10_12 right)
        (next loc_9_12 loc_9_11 down)
        (next loc_10_12 loc_9_12 left)
        (next loc_10_12 loc_10_11 down)
        (patterned loc_5_2 red)
        (patterned loc_6_2 lightblue)
        (patterned loc_5_3 pink)
        (patterned loc_6_3 red)
        (patterned loc_2_5 orange)
        (patterned loc_3_5 green)
        (patterned loc_4_5 blue)
        (patterned loc_7_5 blue)
        (patterned loc_8_5 pink)
        (patterned loc_9_5 green)
        (patterned loc_3_6 orange)
        (patterned loc_8_6 orange)
        (patterned loc_9_6 yellow)
        (patterned loc_2_8 coal)
        (patterned loc_3_8 pink)
        (patterned loc_4_8 red)
        (patterned loc_7_8 blue)
        (patterned loc_8_8 pink)
        (patterned loc_9_8 coal)
        (patterned loc_3_9 lightblue)
        (patterned loc_8_9 yellow)
        (patterned loc_4_11 orange)
        (patterned loc_7_11 orange)
    )

    (:goal
        (forall (?l - location)
            (not (exists (?p - pattern)
                (patterned ?l ?p)))))

    (:metric minimize (total-cost))
)
