name: CI-on-push

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

    with:
      python-version: "3.12"

    secrets: inherit
