name: CI-on-master

on:
  push:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    uses: ./.github/workflows/test.yml

    with:
      python-version: ${{matrix.python-version}}

    secrets: inherit

  deploy:
    needs: [test]
    uses: ./.github/workflows/deploy.yml
